sudo: required
addons:
  apt:
    packages:
      - postgresql-9.4
      - redis-server
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r lox/requirements.txt"
# command to run tests
script: nosetests
