addons:
  postgresql: "9.3"
services:
  - redis-server
  - redis-server
language: python
python:
  - "2.7"
# command to install dependencies
install: "pip install -r lox/requirements.txt"
# command to run tests
script: nosetests
